### ISSUE TITLE
JSON fields in mysql not respecting collation configuration

### ISSUE THREAD

**Issue by opengeek** [cakephp/phinx#1342]
I'm trying out Phinx 0.9.2, and I have a database with `utf8_unicode_ci` collation, which I also specified in my Phinx configuration. However, when it created my tables on the initial migration run, all `json` fields (which seem to be `longtext` when created in mysql) across all tables were set to `utf8mb4_ci`. All other field types were the appropriate `utf8_unicode_ci` collation, including a `mediumtext` one. I did not specify any overrides on the column definitions on any of the tables.

I couldn't find an existing report regarding this so I thought I would enter an issue and see if anyone else can confirm the problem.

**Comment by rquadling** [comment]
Purely a FYI in relation to mysql.

utf8 is an alias for utf8mb3. If you are using utf8_unicode_ci, then this is really utf8mb3_unicode_ci. mb3 does not cover the entire unicode space. This is normally fine for "normal" work, but will break if you allow data to contain certain emoji (for example). In addition to the encoding of the data, the collation can change due to upgrades in the unicode layer that utf8mb3_unicode uses.

At the moment, the current "best" is utf8mb4_unicode_520_ci. This is versioned full mb4. No more space is required to use mb4 over mb3 for those characters that fit into mb3 (remember if you're using utf8, you are already using utf8mb3).

A plus. If the unicode standard changes, your encoding and collation won't change just because you upgraded your server, or copied your db to a server that is using a newer version as a default.

A plus. You can encode and sort using emojis! Why? Hey! If you need happy smiley face before pile of poo then this is a plus, right?

A couple of serious negatives.

Firstly, indexes seem to be binary. I didn't know that until I found that the maximum number of bytes in an index equates to an index containing a single `varchar(255)` in utf8(mb3). In utf8mb4, the equivalent is `varchar(191)`. So, if you are indexing an email address in a `varchar(255)`, you will have issues immediately.

Secondly, upgrading. From the limited work I've done in moving from utf8_general_ci/utf8_unicode_ci to utf8mb4_unicode_520_ci, you will need to essentially dump and import the data. You can use SQL to do the entire per table conversion as well as setting all the columns and the schemas correctly, but be prepared for a wait. Obviously, mitigation techniques are around (creating a new table, using triggers, etc.) all quite standard for processing multi-million row tables with zero downtime.

A minor issue. If you are in the process of converting to a particular encoding/collation, you may need to be using the `COLLATE` clause in your queries if you are expecting textual comparisons. Particularly watch out if you have views that do textual comparisons which you are in the process of upgrading the tables to the new encoding/collation.

**Comment by rquadling** [comment]
In direct response to the JSON encoding issue, from what I've read JSON is a full unicode standard/compliant, so utf8mb4 is the only applicable encoding. If it is not possible to index JSON data in mysql then there's no need for a collation, just an encoding. So, if you were to somehow get the DB to hold JSON in utf8mb3 (or less), then it wouldn't be matching the JSON specification.

**Comment by rquadling** [comment]
https://dev.mysql.com/doc/refman/8.0/en/json.html
> MySQL handles strings used in JSON context using the utf8mb4 character set and utf8mb4_bin collation. Strings in other character sets are converted to utf8mb4 as necessary. (For strings in the ascii or utf8 character sets, no conversion is needed because ascii and utf8 are subsets of utf8mb4.)

**Comment by opengeek** [comment]
Thanks for the followup, @rquadling. I am aware of the utf8/utf8mb4 issues, in general. I just honestly have never made use of the new `json` field type and was curious if it was intended behavior for Phinx to force the collation in this case. But it seems it is not Phinx forcing it at all. I think you've covered my answer and more.
