### ISSUE TITLE
Modular structure

### ISSUE THREAD

**Issue by hotrush** [cakephp/phinx#1401]
Phinx is a framework-free library, but i noticed that it loading half of cakephp as a dependency. For me looks like integrating framework into other framework. Maybe it can be more lightweight and modular. Each framework or cms has it's own database/cache/etc interfaces. For example database operations might work as adapters, just implement any interface and pass as parameter or to container.

**Comment by dereuromark** [comment]
So you complain about cakephp components, but not symfony? :)

        "cakephp/collection": "^3.6",
        "cakephp/database": "^3.6",
        "symfony/console": "^2.8|^3.0|^4.0",
        "symfony/config": "^2.8|^3.0|^4.0",
        "symfony/yaml": "^2.8|^3.0|^4.0"

In fact, those are required to not have to reinvent certain wheels, as such those are not really feasible to just "reprogram" to have no dependencies.

**Comment by hotrush** [comment]
> So you complain about cakephp components, but not symfony? :)

No, i am talking about modularity and useless dependencies. Just a real situation, i am integrating phinx into some kind of old framework. I don't want to use it as standalone app with it's own config and want to integrate into framework. This framework has it's own database and config interfaces and I can use them to load configs and to operate with database. But phinx using it's own and it's weird.

Phinx can have some kind of adapters for database with one interface. And your default one might be optional, but not required. It will be more flexible.

**Comment by lorenzo** [comment]
The dependencies are not useless, as they are actually used internally by phinx. They should not make you nervous as they don’t incur in any performance but for the rest of your application, it only consumes a few extra bytes.

You can do as cakephp the framework does for integrating phinx. It extends some of the classes and configures phinx so that it can be used more naturally with the rest of the ecosystem.

**Comment by joshbmarshall** [comment]
I agree that having the dependencies is a great thing, for example it added the ability to do more complex queries without having to manually escape data in raw SQL by using cake's database library.

However the issue that I have is that the helper functions that cake core installs by default are included on every request, so does bloat the tiny requests (e.g. a REST interface). But more importantly has started giving me errors that functions are already defined where before there was no clash.

My example is that I have incorporated adminer into the management interface so that top level users can access the database directly. Adminer defines the h() function, and this clashes with cake's core functions.php file.

**Comment by lorenzo** [comment]
Yeah, that’s a known issue. We are thinking how to improve the global functions situation

**Comment by lorenzo** [comment]
Yes, a workaround is to make sure the global functions from your project get included first. Cake will not los  its functions of ir detects others with the same name

**Comment by joshbmarshall** [comment]
I can confirm that does the trick :)
