### ISSUE TITLE
Do not rely on composer.json for version

### ISSUE THREAD

**Issue by mbrodala** [cakephp/phinx#1440]
Phinx currently tries to load its `composer.json` for the application version. However, that file might not be present at all, e.g. after a deployment which only includes the bare minimum of required files. Normally the `composer.json` is not necessary at runtime.

From what I see a workflow would be required to set the application version right before or on a new release.

**Comment by dereuromark** [comment]
composer.json is always what you should consider the bare minimum IMO.
Everything else is just over-optimization for the sake of creating issues.

**Comment by mbrodala** [comment]
I've just changed our deployment to include the `composer.json`. I'm still not too fond to have (normally) unused files lying around but for now it fixes the issue we saw (`migrate` failing with exit code 255 due to this.)

**Comment by dereuromark** [comment]
You should never manually do this anyway.
This is what https://github.com/cakephp/phinx/blob/master/.gitattributes#L11-L21 is for.

**Comment by mbrodala** [comment]
This is a misunderstanding: we deploy a complex application which uses many 3rd party packages (including Phinx) and prefer to not have any unused files (including `composer.json`) reside on the server. This is not a single package we are talking about. ;-)

**Comment by dereuromark** [comment]
And the problem is on your side here, as already explained. File size, and complexity doesn't matter.
You just dont do this overopt. There is no benefit in it, I can tell you because whatever complex system you got, we have it 10x more at Spryker. And filedisk size is irrelevant compared to the issues you introduce by manually removing files in the autoloader part (vendor) of your deploy.
