### ISSUE TITLE
Bug with setting uuid as primary key

### ISSUE THREAD

**Issue by Modicrumb** [cakephp/phinx#1464]
When setting uuid as primary key outside of Create Table migrations
ie

`$this->table('some_table')->removeColumn('id')->addColumn('id', 'uuid', ['null' => false])->addPrimaryKey(['id']);`

Cake makes an error in assigning this PK, when I look at the create table statement I see 

PRIMARY KEY (`id`(4))

When I set PK when Creating a table though with the primary_key option it works just fine
ie 
```
$this->table('some_table', ['id' => false, 'primary_key' => ['id']])->addColumn('id', 'uuid', [
            'null' => false,
        ]);
```

**Comment by djcvijic** [comment]
Can you specify which database adapter you are using?

I may get to this issue soon, but pull requests are appreciated!

**Comment by Modicrumb** [comment]
Using MySQL
```
    'Datasources' => [
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
```

**Comment by djcvijic** [comment]
First of all, there is no method `addPrimaryKey` as far as I know, so I'll assume you meant `changePrimaryKey`.
When I make that change, the error I get is `PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id'`.

I assume it's because that sequence of calls is trying to create the `id` column, then drop it, then create it again, all at the same time, and there might be a problem with how the query planner sorts these operations. You could remedy this by splitting up all the sub-calls, all followed by `->save()`.

Or, just avoid initially creating the `id` column implicitly, and create it yourself:
```
$this->table('some_table', ['id' => false])->addColumn('id', 'uuid', ['null' => false])->changePrimaryKey(['id'])->save();
```

Or if you didn't care about calling changePrimaryKey separately, by far the most simple approach would be to alter the type of the column after creating the table:
```
$this->table('some_table')->changeColumn('id', 'uuid', ['null' => false])->save();
```

In light of there being so many ways to accomplish this task, I think there is nothing that needs fixing. I'd like another collaborator or contributor to check this before closing though, to see if we need to address the problem that might exist with query planning.

**Comment by Modicrumb** [comment]
Strangely I don't see documentation for 
`addPrimaryKey`
though it seems to work regardless meaning it does exist?

I'll have to test the changePrimaryKey method to see if it behaves properly later, if that works then I'm fine. Strangely I was simply copying a coworkers code when I used the addPrimaryKey method....

**Comment by Modicrumb** [comment]
Method changePrimaryKey doesn't exist in Phinx\Db\Table
Call to undefined method Phinx\Db\Table::changePrimaryKey()

Am I doing something wrong here?

**Comment by Modicrumb** [comment]
I ended up just doing 

$this->execute('ALTER TABLE some_table  ADD PRIMARY KEY (some_id)');
