### ISSUE TITLE
Phinx with SQLITE Call to a member function execute() on boolean

### ISSUE THREAD

**Issue by justtoprogram** [cakephp/phinx#1500]
Hi,

I am trying to use Sqlite3 with Phinx, however when I attempt to insert data into the DB, it fails. Below is my configuration file:

paths:
    migrations: '%%PHINX_CONFIG_DIR%%/../../DBMigrations/kiosk/migrations'
    seeds: '%%PHINX_CONFIG_DIR%%/../../DBMigrations/kiosk/seeds'

environments:
    default_migration_table: phinxlog
    default_database: production
    production:
        adapter: sqlite
        name: /home/tim/test.db
        suffix: '.db'

And I am receiving an error as above in the title:

![image](https://user-images.githubusercontent.com/44853786/52527835-fedff300-2d1a-11e9-8ea2-2c4804241c30.png)

Do you know what the issue may be?

Cheers,
Tim

**Comment by garas** [comment]
The line 219 comes after `prepare()`
https://github.com/cakephp/phinx/blob/e1698319ad55157c233b658c08f7a10617e797ca/src/Phinx/Db/Adapter/PdoAdapter.php#L218-L219

However "If the database server cannot successfully prepare the statement, PDO::prepare() returns FALSE" ([php.net](http://php.net/manual/en/pdo.prepare.php)), and `execute()` is called on `false` without check.

There is something wrong with prepared query, maybe something wrong with seed data or  `saveData()` or `bulkinsert()`.
Try the latest Phinx version.

**Comment by kevinbreacher** [comment]
Hi,

The problem is that you have an older version where the problem still exist. 
Furthermore, it's a good habit to separate the migration from the seeding, at least while you are still testing your DB. 

Like garas said, it has been already fixes in the latest version of Phinx (0.10.7).
Here is the link : https://github.com/cakephp/phinx/pull/1313

Have a good evening!

Kevin

**Comment by lorenzo** [comment]
already fixed
