### ISSUE TITLE
Inconsistency with save and update methods in docs

### ISSUE THREAD

**Issue by djdavies** [cakephp/phinx#1519]
In the generated docs in migration class we have:
`     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.`

However in http://docs.phinx.org/en/latest we see save() being used many times with the table class.
`        $table = $this->table('users');
        $table->removeColumn('short_name')
              ->save();`

**Comment by dereuromark** [comment]
Are you able to help our and create a PR with the suggested fixes in documentation?

**Comment by jamescrowley** [comment]
Can anyone clarify *why* ? If so I'd be happy to update the docs. I was just checking the docs for an explanation on this - we've been accidentally using ->save() despite the comment and want to understand what the impact is.

**Comment by MasterOdin** [comment]
It has to do with phinx being able to automatically determine what should happen on a rollback. The relevant code for save is this:
https://github.com/cakephp/phinx/blob/b6c2c590c3c67da169667ed64ddc21c4f261d3d0/src/Phinx/Db/Table.php#L684-L691

where we see that calling `save()`, if the table exists, you get `update()` and if it doesn't `create()`.  Depending on which of those two functions get called, changes how phinx operates on a rollback. `update()` will cause it to just reverse any operations on the table while `create()` will drop the table.


Now, look at the following migration where it's the first one I've got and I want to add a new table to my schema:
```
<?php

use Phinx\Migration\AbstractMigration;

class Test extends AbstractMigration
{
    public function change()
    {
        $this->table('test')
            ->addColumn('test', 'string')
            ->save();
    }
}
```

Running it, will give me:
```
$ sqlite3 db/test.sqlite3
sqlite> .tables
phinxlog
$ bin/phinx migrate
# output omitted
$ sqlite3 db/test.sqlite3
sqlite> .tables
phinxlog  test
sqlite> SELECT * FROM test;
sqlite> .schema test
CREATE TABLE `test` (`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `test` VARCHAR NULL);
```
We see the table doesn't exist at first, I run migrate and it is created. `save()` in this instance is calling `create()` as the table does not exist. 

and then running rollback will give me:
```
$ bin/phinx rollback
# output omitted
$ sqlite3 db/test.sqlite3
sqlite> .tables
phinxlog  test
sqlite> .schema test
CREATE TABLE `test` (`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT);
```
We see on the rollback, the `addColumn` operation is undone, but the table itself remains, due to the fact that `save()` called `update()` as the table existed.


Now, when using the `up()` method, this difference is not really important as you explicitly are telling phinx how to rollback in the `down()` method, but when using `change()`, you have to be explicit with what the operation (creation or updating) you are doing on the table.

Hopefully that explains it.
