### ISSUE TITLE
BugFix for SQLite ChangeColumn 

### ISSUE THREAD

**Issue by SlavaAurim** [cakephp/phinx#2035]
https://github.com/cakephp/phinx/blob/ca7250585e0567d0983746035eaf8a1f912f8b72/src/Phinx/Db/Adapter/SQLiteAdapter.php#L882

The current regexp expression specified above, incorrectly parse this simple definition and DO NOT trim the leading "CREATE TABLE ..." prefix:
```sql
CREATE TABLE "users"\n
 (\n
 \t    id INTEGER not null\n
 \t    \t    primary key autoincrement,\n
 \t    email VARCHAR(75) not null,\n
 \t    password VARCHAR(128) not null,\n
 \t    roles TEXT\n
 )
``` 

Please change regexp pattern to one of the working variants:
```php
"/^CREATE TABLE .*\(/Uis",
```
or
```php
"/^CREATE TABLE .*\s+\(/Ui",
```

**Comment by MasterOdin** [comment]
Would you be able to make a PR with your suggested changes @SlavaAurim? The only change I have would be renaming `quoteCreateSql` to `normalizeCreateSql` since it's adjusting newline spacing and such.

Please also include some tests in `tests/Phinx/Db/Adapter/SQLiteAdapterTester.php`. You can use the `$this->adapter->execute()` method to create a table outside of phinx with denormalized quotes or newline spacing. A quick example would be:

```php
    public function testAddColumnToCreateTableWithNewline()
    {
        $this->adapter->execute("CREATE TABLE \"users\"\n( id INTEGER NOT NULL )");
        $table = new \Phinx\Db\Table('users', [], $this->adapter);
        $table->addColumn('foo', 'string');
        $table->update();

        $columns = $this->adapter->getColumns('users');
        $this->assertSame('id', $columns[0]->getName());
        $this->assertSame('foo', $columns[1]->getName());
    }
```

where this test was failing before your patch, and now passes.

**Comment by SlavaAurim** [comment]
Sorry, but I couldn't make PR, because I don't have the skills with git. All your ideas is ok.

**Comment by InvisibleSmiley** [comment]
I also ran into this, but while trying to add new columns to an existing table created manually (not using Phinx).

In my case, fixing the CREATE TABLE to match the regex wasn't enough. There's also a regex in getAddColumnInstructions that (since 0.12.4) requires the original column names to be quoted. In my case they were not quoted at all (again, table created manually).

Please keep this case in mind when you implement a fix.

In my case I'll just fix the original table creation SQL (quoting the column names) but I have to tell you that this was really hard to spot. The effect of the behavior since 0.12.4 was simply that the "add column" operation turned into a no-op because the regex didn't match anything. Hence any accesses to the to-be-added column subsequently failed.

**Comment by dereuromark** [comment]
Is anyone able to provide a PR?
After this one, we could release one last patch release of the 0.12 series.

**Comment by MasterOdin** [comment]
@dereuromark I'll put together a PR at some point in the next week.
