### ISSUE TITLE
PHINX_CONFIG_DIR overwrite

### ISSUE THREAD

**Issue by GoldraK** [cakephp/phinx#2036]
Hello,
I am using phinx in a project and I am creating a package that uses it.
I have seen that it is possible to overwrite variables before using PhinxAplication

https://book.cakephp.org/phinx/0/en/commands.html#running-phinx-in-a-web-app

> To modify configuration variables at runtime and override %% PHINX_DBNAME %% or other another dynamic option, set $ _SERVER ['PHINX_DBNAME'] before running commands. Available options are documented in the Configuration page.

But it's not working

```php
$_SERVER['PHINX_CONFIG_DIR'] = __DIR__.'/../';

$app = new PhinxApplication();
$app->setAutoExit(false);
$app->run(new StringInput('migrate'), new NullOutput());
```

I have looked at the package and in this commit is the getenv that collects the configuration

https://github.com/cakephp/phinx/commit/2ce860d03732e538db3ccd43b5349e8aee0d30df

But then you look at the master or version 12 tags and it disappears.I am using version 0.12.8

What is the correct way to do it?

Thanks.

**Comment by MasterOdin** [comment]
If your configuration file has the contents (for example):

```json
paths:
  migrations: %%PHINX_CONFIG_DIR%%/db/migrations
```

Are you saying that the `%%PHINX_CONFIG_DIR%%` _inside_ the configuration file is not getting replaced properly?

**Comment by MasterOdin** [comment]
Alright, so the bit of code that sets up the tokens to be replaced is located at:

https://github.com/cakephp/phinx/blob/ca7250585e0567d0983746035eaf8a1f912f8b72/src/Phinx/Config/Config.php#L422-L435

So setting the `$_SERVER` or `$_ENV` value for any token _other_ than `PHINX_CONFIG_PATH` and `PHINX_CONFIG_DIR` work as you would think in terms of replacement. The two `PHINX_CONFIG_*` variables are special in that they are always set to point towards the location of the config file (and its surrounding directory). While we should make a note about these variables, I do think that not being able to override their value does make sense, as otherwise could lead to some surprising behavior for maintainers of an app, and how similar applications expose a `CONFIG_PATH` type env var.

Would just using a custom token in your config work for you, like `PHINX_DATA_PATH` or something to set for the paths, instead of using `PHINX_CONFIG_DIR`?
