### ISSUE TITLE
[MariaDB] Setting NULL as default value is ignored

### ISSUE THREAD

**Issue by bkrnetic** [cakephp/phinx#2059]
Hello,

I use MariaDB 10.3.31 version and migration ignores `null` as default value.

I use it this way:

```
$table->addColumn('foo', 'string', ['null' => true, 'default' => NULL])
```

It doesn't work for timestamp fields either...

Are you familiar with this issue? Is it maybe something related to MariaDB?

To me it seems like a basic feature. 🤷‍♂️  Hopefully somebody can help me out!

Best regards,
Bruno

**Comment by MasterOdin** [comment]
We don't append the `DEFAULT NULL` for any DB adapter:

https://github.com/cakephp/phinx/blob/468c635ef8aeacd0ab69d0640aea408598c27038/src/Phinx/Db/Adapter/PdoAdapter.php#L598

This is fine though as the databases (at least by default) implicitly assume a default of null if none are set and the column is nullable. Can you configure MariaDB where this isn't true so that `foo varchar NULL` is not equivalent to `foo varchar NULL DEFAULT NULL`?

**Comment by bkrnetic** [comment]
> We don't append the `DEFAULT NULL` for any DB adapter:
> 
> https://github.com/cakephp/phinx/blob/468c635ef8aeacd0ab69d0640aea408598c27038/src/Phinx/Db/Adapter/PdoAdapter.php#L598
> 
> This is fine though as the databases (at least by default) implicitly assume a default of null if none are set and the column is nullable. Can you configure MariaDB where this isn't true so that `foo varchar NULL` is not equivalent to `foo varchar NULL DEFAULT NULL`?

You are right @MasterOdin. Thanks a lot, wasn't aware of this. I'm closing the issue.
