### ISSUE TITLE
Proper way to add new table to an existing database without deleting existing data?

### ISSUE THREAD

**Issue by zkwbbr** [cakephp/phinx#2072]
For example you already have a migration file like this that creates "table_A":

```
class CreateTableA extends \Phinx\Migration\AbstractMigration
{
    public function change()
    {
        $this->table('table_A')
            ...snip...
            ->create();
    }
}
```

Later on you need a new table (table_B) so you create another migration file:

```
class CreateTableB extends \Phinx\Migration\AbstractMigration
{
    public function change()
    {
        $this->table('table_B')
            ...snip...
            ->create();
    }
}
```
Now when you run `vendor/bin/phinx migrate` you will get an error saying table_A already exists. Does this mean you need to check if table_A already exists before running  `create()` in `CreateTableA` migration file? For example:

```
public function change()
{
	if (!$this->hasTable('table_A')) {
		$this->table('table_A')
			...snip...
			->create();
	}
```
}

Is this the way to add new tables without deleting existing data or is there a proper way?

**Comment by garas** [comment]
If you already have tables, you can mark migrations as applied with `phinx migrate --fake`.

**Comment by zkwbbr** [comment]
@garas Thanks for the reply. I tried `phinx migrate --fake` however it did not create the new table that I wanted to create. It seems the `--fake` flag only simulates. It also appears to be undocumented?

**Comment by garas** [comment]
Flag is currently only documented in `bin/phinx migrate --help`. You can read original PR https://github.com/cakephp/phinx/pull/1318 for more information.

When using `--fake` flag, you can also specify `-t TARGET` to migrate only some versions.

To undo some migrations, you can now run `rollback --fake -t TARGET` or manually remove some entries from `phinx_log` table. Then use real `migrate` command.

**Comment by zkwbbr** [comment]
It worked thank you, but something weird happened though.

I tested further, I dropped all the tables so I am starting from scratch. Ran `phinx migrate` several times and for some reason it's no longer complaining that the tables already exists. I then continued to add a new migration to see if it will complain and it did not. It created an additional table on top of the existing ones without any problems.

This is all just using plain `phinx migrate` without flags.  It suddenly stopped throwing errors that tables already exists. What do you make of it?

**Comment by MasterOdin** [comment]
That's normal and expected phinx operation. Phinx keeps track of migration statuses in the `phinxlog` table. When you run `phinx migrate` or `phinx rollback`, it saves the completed status in that table, so that it can tell you the state your DB is in compared to the migrations you have.

When starting phinx with an existing DB, your first migration might be to setup the structure that's already in your DB, and then future migrations would be your new changes you want to make going forward. In this case, you'd want to use the `--fake` flag so that your first migration is marked as having been run, but without actually running any of the migration logic. Future uses of `phinx migrate` would see that the first migration (and any others you've faked) had been run, and so only run any subsequent migration that hadn't been run.

I would suggest using the [status command](https://book.cakephp.org/phinx/0/en/commands.html#the-status-command) (`phinx status`) at different phases of `migrate` and `rollback` to get a sense of the bookkeeping that Phinx is doing with regards to the migrations that are run.

**Comment by zkwbbr** [comment]
@MasterOdin Thank you, that makes sense. The phinx log may have been empty when I first encountered the "already exists" error. Look all good now, thanks again.
