### ISSUE TITLE
Weird packagist name `robmorgan/phinx` instead `cakephp/phinx`

### ISSUE THREAD

**Issue by michael-schaefer-eu** [cakephp/phinx#2089]
As this seems to be an _official_ cakephp project `https://github.com/cakephp/phinx/`,

why is this package still under `https://packagist.org/packages/robmorgan/phinx` (so I need to `require robmorgan/phinx` instead of `require cakephp/phinx` ) ???

I mean, this is very suspicious for a professional developer who is concerned about security!

If this is due to history and has no technical reasons, please change it :1st_place_medal:

**Comment by markstory** [comment]
> If this is due to history and has no technical reasons, please change it 🥇

The reason for this naming is historical. Rob Morgan was the original maintainer and the cakephp team and other phinx maintainers continued maintenance after Rob moved to other projects.

Renaming the composer alias wasn't done earlier because it breaks all existing usage, and the 'value' of that change is pretty low. We might be able to add another alias and publish to both aliases, but figuring that out it hasn't been a priority.

**Comment by michael-schaefer-eu** [comment]
I see, thank you for the explanation.

Should I close this issue then or should I leave it open for the future ?

**Comment by markstory** [comment]
We can leave it open for now. I don't think there is a great solution that isn't disruptive to existing users unfortunately.

**Comment by michael-schaefer-eu** [comment]
Alright, @markstory .

Maybe it can be changed for the next major version, as it would introduce breaking changes anyway ... so v `1.0.0` I'd guess :)

**Comment by MasterOdin** [comment]
Given the current naming, this could just be done on a `0.x` release as these are allowed breaking changes. Perhaps better to pull of the bandaid sooner rather than later if there is a desire to move it under the `cakephp/` hierarchy on packagist. I'm not sure how possible it is to publish to both the old and new namespace for a few versions to make the transition a bit easier, or if it'll just be that as of (say) `0.12.10` `robmorgan/phinx` is abandoned and points to `cakephp/phinx` for `0.13.0` onward.

**Comment by markstory** [comment]
> I'm not sure how possible it is to publish to both the old and new namespace for a few versions to make the transition a bit easier, or if it'll just be that as of (say) 0.12.10 robmorgan/phinx is abandoned and points to cakephp/phinx for 0.13.0 onward.

Publishing to both packages is the part I'm not sure of either.

**Comment by othercorey** [comment]
> > I'm not sure how possible it is to publish to both the old and new namespace for a few versions to make the transition a bit easier, or if it'll just be that as of (say) 0.12.10 robmorgan/phinx is abandoned and points to cakephp/phinx for 0.13.0 onward.
> 
> Publishing to both packages is the part I'm not sure of either.

We would need 2 repos with one pointing to the legacy package.

**Comment by michael-schaefer-eu** [comment]
Maybe the easiest way could be the composer [replace](https://getcomposer.org/doc/04-schema.md#replace) option:

> Map of packages that are replaced by this package. This allows you to fork a package, publish it under a different name with its own version numbers, while packages requiring the original package continue to work with your fork because it replaces the original package.

for example, the _v 0.13.0_ `composer.json` could contain:

```json
"name": "cakephp/phinx",

"replace": {
    "robmorgan/phinx": "0.12.10"
}
```

**Comment by MasterOdin** [comment]
I'm not sure that would be much benefit over just forcing people to use the new namespace. I also think having two repositories is probably more effort than wanted as well.

If there was a desire to actually make this `cakephp/phinx`, then I'd say just rip off the band aid and do it and let the ecosystem correct itself. It's not _that_ much effort to update the codebase for the namespace as there's not any other robmorgan packages that exist.

**Comment by dereuromark** [comment]
Currently there is no real benefit of going that direction.
