### ISSUE TITLE
DEFAULT_GENERATED being added to queries.

### ISSUE THREAD

**Issue by ghost** [cakephp/phinx#2138]
### Versions: 
phinx: 0.11
mysql: 8+
pho: 7.2

Refering to: https://github.com/dbeaver/dbeaver/issues/10797

---
when creating a colum which has CURRENT_TIMESTAMP as the default value, mysql adds 'DEFAULT_GENERATED' into the extra column.

This then gets added to any alter statements and causes a syntax issue. 

---
### REPRODUCTION:
####Create a table with a datetime field with CURRENT_TIMESTAMP as the default value.
```
CREATE TABLE `test_table` (
	`id`  INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(80) NOT NULL,
	`last_changed` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
```
####using phinx to rename the column
```
public function change(){
    $this->table('test_table')
            ->renameColumn('last_changed', 'updated_at')
            ->update();
}
```

**Comment by cergfix** [comment]
The behaviour is the same in the latest version as well. Seems like whatever is in the EXTRA column is simply appended to the rename operation query without any filtering https://github.com/cakephp/phinx/blob/0.x/src/Phinx/Db/Adapter/MysqlAdapter.php#L568.
I wonder if the fix is just to erase the DEFAULT_GENERATED, e.g. `$extra = ' ' . str_replace('DEFAULT_GENERATED', '', strtoupper($row['Extra']));`
