### ISSUE TITLE
(At least) Non-interactive commands should write errors to STDERR

### ISSUE THREAD

**Issue by InvisibleSmiley** [cakephp/phinx#2270]
Right now commands like `migrate` write errors to STDOUT. This is wrong. Errors, especially from commands that are commonly used non-interactively, need to be written to STDERR so that scripts executing Phinx can easily distinguish between information (STDOUT) and errors (STDERR), possibly redirecting either of them to different locations.

Here's how:
https://symfony.com/doc/current/console/style.html#writing-to-the-error-output

**Comment by derikb** [comment]
+1 to this. We are using AWS CodeDeploy and have phinx migrations running via a bash script. Because the errors aren't going to stderr the script just happily continues on its way when phinx errors out without triggering any of our error handlers.

**Comment by dereuromark** [comment]
Maybe someone wants to make a PR. I am sure it can be fast tracked.

**Comment by derikb** [comment]
I would if I had the slightest clue how any of this works. We don't use Symfony otherwise, so it's a bit of a learning curve to figure out where to even make this happen...

would it be in the various commands at this point (using Migrate as an example):

https://github.com/cakephp/phinx/blob/31d837c17d6dc294d44f0b17331066548ac8c032/src/Phinx/Console/Command/Migrate.php#L96 where instead of `writeln` one would use the SymfonyStyle error style per the link in the issue description?

**Comment by InvisibleSmiley** [comment]
I'll try to work on this within the next two days. Originally I thought it was so easy and straightforward that I only created the issue with pointers at the solution path, but then lost track of it.

Basically it's merely adding this at the beginning of all command execute methods and then replacing $ouput by $errorStyle whereever output shall be written to STDERR (if available):

```
$io = new SymfonyStyle($input, $output);
$errorStyle = $io->getErrorStyle();
```
(of course SymfonyStyle needs to be imported).
