### ISSUE TITLE
Unable to seed rows using CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by phrfpeixoto** [cakephp/phinx#2297]
Hello, I'm trying to write a simple seeder:

```php
class MySeeder extends AbstractSeed
{
    public function run(): void
    {
        $data = [
            [
                'user_name' => 'Administrator',
                'user_creation' => 'CURRENT_TIMESTAMP',
            ]
        ];
        $table = $this->table('users');
        $table->insert($data)->saveData();
    }
}
```

Executing this seeder fails:

```
[PDOException (22007)]
  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'CURRENT_TIMESTAMP' for column 'user_creation' at row 1
```

I explored the code a bit, and tried using Literal and Expression, but got the same result.
Is there a way to achieve this?

**Comment by MasterOdin** [comment]
Yeah, this is currently not possible, and is a bug in this block of code:

https://github.com/cakephp/phinx/blob/5f9ee844fdf3a34af7aac211f9463758c35bc18b/src/Phinx/Db/Adapter/PdoAdapter.php#L378-L415

The root here is that when inserting, we create a prepared statement where all values are then binded. Stuff like `CURRENT_TIMESTAMP` (or any function really) cannot be a binded parameter, but should be in the SQL directly. As such, the fix would be that when we go to construct the SQL statement, instead of just saying all values are going to be binded, we need to step through each, and either insert the literal (if using `Literal`) or a `?` to be binded.

**Comment by MasterOdin** [comment]
I think the bug also exists in the `PdoAdapter::insert` method as well, so will want to fix it in both places.

**Comment by MasterOdin** [comment]
Using literals is now supported as of `0.16.3` released today.
