### ISSUE TITLE
Rollback on exception

### ISSUE THREAD

**Issue by AndreasBackx** [cakephp/phinx#308]
In issue #307 there is a PDO exception that occurs and after this the database doesn't get fully migrated and is left partly migrated. Let's say the exception was because a stupid mistake and I fixed it so I want to migrate. I wouldn't be able to migrate because of the previous failed migration that created some columns but threw an exception in the middle of the migration. If there is an exception, Phinx should rollback the migrations that were made so the next migration can proceed.

**Comment by evought** [comment]
Just got bit by this myself with the following code (trimmed):

        $table = $this->table('CONTACT_URL', ['id'=>'URL_ID']);
        $table  ->addColumn('UID', 'string', ['limit'=>45])
                ->addColumn('URL', 'string')
                ->addColumn('MEDIATYPE', 'string', ['null'=>true])
                ->addColumn('VALUETYPE', 'string', ['limit'=>40, 'null'=>true])
                ->addColumn('PREF', 'integer', [ 'limit'=>2,
                                                 'null'=>true,
                                                 'signed'=>false ] )
                ->addForeignKey( 'UID', 'CONTACT', 'UID',
                                [ 'delete'=>'CASCADE',
                                  'update'=>'CASCADE'
                                    ])
                ->create();
        
        $table = $this->table('CONTACT');
        $table->dropColumn('URL')->update();

Basically, I am taking a field from an existing table and breaking it out into its own entity, then removing the column from the original table. Clearly "dropColumn(..)" in my code should be "removeColumn(..)" and this code fails. If I run "phinx status", it reports the migration as "down", as it should (but perhaps logging "failed" would make sense?)

I then fix the error and use "phinx migrate" to apply it. It fails because CONTACT_URL already exists. "phinx rollback" also, of course, fails. The only fix is to a) manually correct the state or b) drop and recreate the database from the first migration. If this fails in development, as it did, this is not so bad, but if a mistake in migration script makes it to production... the entire purpose of a migration tool is defeated.

Internally, if phinx naively calls the down() method (of course, in this particular case, down() actions are generated because the mistake occurred in a change() method), the transaction may still fail because the up() method never completed. Two solutions, one for the implementation and one for the user:

1) The user can be warned to test ALL rollback actions in their down() method because they are not guaranteed that the up() actions ever completed. Then the implementation could try to run the down() method on failure and any inapplicable actions would be skipped. Phinx provides predicates for the programmer to test the schema and do this appropriately, but it would probably require an explicit warning and an example in the documentation (I might even be convinced to write the example if I figure out what an ".rst" file is...). This would work for cases where an explicit up()/down() is provided.

2) For cases where a change() method is provided, the migration script does not have the opportunity to do this. In this case, phinx would have to make that effort in its own generated down() action, testing each rollback before executing it. Alternately, phinx could keep a journal of the change() steps applied and rollback ONLY those actions successfully completed before an exception is thrown.

There are undoubtedly errors which would *still* potentially leave things in an inconsistent state, but this should cover 95%+ of the useful cases. The remainder would be covered by checkpointing the production DB before running a migration or pre-testing a migration against a clone of the production data and is probably beyond what phinx can reasonably be expected to do.

**Comment by berarma** [comment]
We can use transactions inside our migrations like this:

```php
public function up()
{
    $this->adapter->beginTransaction();
    ...
    $this->adapter->commitTransaction();
}

public function down()
{
    $this->adapter->beginTransaction();
    ...
    $this->adapter->commitTransaction();
}
```

This code will rollback the migration when interrupted by an error or exception. It will also make the migration faster when updating a lot of rows in a table. I haven't tried it in the change() method but I guess it should work too.

We could implement this change in the ``AbstractMigration`` class or a custom subclass, with a conditional switch in the ``Migration`` class to enable/disable the automatic transaction.

This won't work for schema changes in MySQL as already noted in the comments, but it will be still useful for data changes.

**Comment by berarma** [comment]
I've noticed the ``Environment`` class already does this when running migrations. Yet I think it isn't working for me.

**Comment by schlndh** [comment]
Check PR #627, but note that as explained it doesn't work on MySQL when you use `ALTER TABLE` or similar statements.

**Comment by mcapodacqua** [comment]
Any news here? This is a kind of expected behavior for every adapter

**Comment by lorenzo** [comment]
This is automatically done for postgres, but it is not possible to do in Mysql
