### ISSUE TITLE
Auto migrating up and down

### ISSUE THREAD

**Issue by alexbowers** [cakephp/phinx#475]
"When creating or updating tables inside a change() method you must use the Table create() and update() methods. Phinx cannot automatically determine whether a save() call is creating a new table or modifying an existing one."

That is a quote from the documentation. However, couldn't we determine what was happening based on a simple internal call of hasTable() ?

If the hasTable is false, then they are creating the table, if it is true, they are updating the table.

**Comment by shadowhand** [comment]
@robmorgan any thoughts on this? I'm not sure what the intent was.

**Comment by arlaneenalra** [comment]
An interesting note on this I've just run into a situation where change and save did something unexpected.  (I hadn't seen the above line in the docs yet).

Sequence:

* create a table using save operation and allowing phinx to implicitly create an id column
* rollback migration

Result:

The table is left behind with only and id column since it was not explicitly added.

**Comment by dereuromark** [comment]
Whats the status on this 2+ year old issue?
