### ISSUE TITLE
Phinx Export Feature

### ISSUE THREAD

**Issue by robmorgan** [cakephp/phinx#5]
It would be nice to run `phinx --export` to export a json/xml/SQL representation of your database migrations. What purpose would this serve though?

**Comment by weemen** [comment]
+1 It would help me to get a nice solution for this problem: http://stackoverflow.com/questions/28792430/workflow-with-database-create-alter-and-drop-commands-and-web-applications-in-pr

**Comment by RQuadling** [comment]
After a few months, we clear out our migrations. After a year and 5 developers, we had well over 200 migrations. And that was from a DB that was NOT phinx controlled. When we deploy a feature branch, we clear out the migrations and rebuild our base install.sql. We also have a preset set of data which is retrieved from the live DB so that a new developer gets a decent clean set of data and a completed DB schema.

Having a standardised approach (one which we can expand upon to include our specifics) would be a great feature.

**Comment by nickdietel** [comment]
+1 would be helpful for someone who needs to review/debug migrations. Also it would support executing queries on another machine without phinx.

**Comment by zondor** [comment]
+1 for export feature to compact big list of migrations in long project.
+1 running automation tools became faster, running 1 sql file rather then all migrations

As extra will be nice to have first migration generation from existing database. As phinx is really useful in custom projects, others frameworks already have database migrations and seeding. But custom projects usualy already have database and its regular monky job converting sql to phinx

**Comment by wweaver** [comment]
What about a way to reconcile the files down to minimal creates and updates. Meaning if a table is created in one migration, then updated in another, to be able to reconcile this down to one file that has a create? I can see this not being quite so simple, especially if there are multiple things happening in one migration, but it still would be a nice to have.

Another plus might be to have the files generated into subdirectories by year/month so that there aren't so many files in one directory. Right now my company is up to 834 files in almost 2 years.

**Comment by celorodovalho** [comment]
:+1:

**Comment by washingtonphp** [comment]
+1 on that

**Comment by foalford** [comment]
+1 In fact missing of this feature makes me hesitate of adding phinx into my project.

1. Plain SQL is easy to review and be inspected on in troubleshooting. 
2. Less dependency, i.e. phinx, less moving parts in automated deployment.

**Comment by MightyMimi** [comment]
+1

**Comment by masom** [comment]
@foalford Phinx is amazing, don't let that missing feature stop you from using it.

**Comment by foalford** [comment]
Well thanks for caring. Initially I was trying to see if it's worth of contributing my code. Before doing that, I found [liquibase](http://www.liquibase.org/), which quite fit into my needs. Also I think that it is a good competitor for phinx.

**Comment by JayPHP** [comment]
#1127 SQL Dump option has now been merged. If JSON / XML dump is still a requirement, please create a new issue, as this has aged.
