### ISSUE TITLE
Global installation

### ISSUE THREAD

**Issue by salarmehr** [cakephp/phinx#587]
I there any reason you did not advice installing phinx globally in the documentation? `phinx init` is far more user-friendly than `php vendor/bin/phinx init` 

Also isn't it better `mkdir migrations` be run by `init` automatically`?

**Comment by w2pc** [comment]
You referring  to just calling init  without having to put the path? That
is a bad idea. You would still have to have something to clarify that it is
a phinx init command vs another init command.

You could always make a bash alias. I for one don't want it globally.

**Comment by elliotwms** [comment]
I'm pretty sure they're talking about running `phinx init` as opposed to `php vendor/bin/phinx init`,

In which case you'd want to run `composer global require` as opposed to `composer require` when installing phinx (and make sure that you add the composer global install path to your shell's PATH variable)

**Comment by elliotwms** [comment]
It looks like they've updated their post to specify that it should be `phinx init` as opposed to simply `init`, which would be a nightmare

**Comment by w2pc** [comment]
You can already install any composer package globally ;) Just like you said
.

**Comment by salarmehr** [comment]
@w2pc  Yeah, I mean it is better to advice global installation in docs.

**Comment by elliotwms** [comment]
I don't know if it's a better option (as you should be installing phinx in `require-dev` anyway so you'd effectively be installing it twice), but it's certainly a valid one. I personally have it installed globally so I can use it outside my vagrant box as `phinx`

**Comment by salarmehr** [comment]
@elliotwms  Why should we add Phinx to `reuire-dev` if it is installed global?

**Comment by elliotwms** [comment]
We do it because we run Phinx from within our vagrant box and from our host machines:

Installed globally on the host machine it allows us to create new migrations without having to SSH into the VM, and putting it in require-dev ensures that the VM has a copy of Phinx it can run any time it is provisioned (as we need to run the migrations from within the VM as Phinx can't do SSH tunnelling through Vagrant yet)

Also it can be a little daunting for newer developers installing with Composer globally; you have to figure out adding things to PATH and so on and so forth, so it always helps to have a copy installed automatically with the Vagrant box

**Comment by dereuromark** [comment]
Having it as require dependency seems the most useful case, everything else is a possible tripping stone.
