### ISSUE TITLE
ConfigInterface and concrete Config class are used inconsistently in AbstractCommand

### ISSUE THREAD

**Issue by cullylarson** [cakephp/phinx#605]
Currently the `AbstractCommand::setConfig` function takes a `ConfigInterface` object, and sets it as the value of `$config`.  However, the `AbstractCommand::getConfig` function returns a concrete `Config` class instance.  How can `$config` ever be set to a concrete `Config` class instance if its setter function only takes a `ConfigInterface`?  This is inconsistent, and negates the benefit of using an interface for config stuff.

If this is fixed, you'll have to check the commands to make sure that the function calls made on the object returned from `AbstractCommand::getConfig` are defined in the `ConfigInterface` interface.  For example, the `Create` command currently calls `$this->getConfig()->getMigrationBaseClassName()`.  However, `getMigrationBaseClassName()` is not defined in the `ConfigInterface` interface.

**Comment by rquadling** [comment]
Amending the interface introduces a BC for anyone having built their own class from the interface and not from the abstract.

If you can put together a PR, then I'm sure Rob will take a look at it.

**Comment by cullylarson** [comment]
Another solution might be to get rid of `ConfigInterface` entirely.  It's basically a container object.  I'm not sure how much benefit you get out of making it an interface, over just subclassing `Config`.

**Comment by rquadling** [comment]
Dropping the interface wouldn't be my call (I'm just an occasional contributor).

**Comment by cullylarson** [comment]
@rquadling My comment wasn't directed to anyone in particular, just adding to the conversation in case any action is taken on this in the future.

**Comment by rquadling** [comment]
That's OK. I think consistency shouldn't be sacrificed without good cause.

**Comment by cullylarson** [comment]
Well, it's already inconsistent. You either change `AbstractCommand::getConfig` to return a `ConfigInterface` (and make sure all of the functions currently defined in `Config` are also defined in `ConfigInterface`, from which there are many currently missing), or you just dump `ConfigInterface` altogether.  Currently there are more references to the concrete `Config` implementation than there are to `ConfigInterface`.  Getting rid of `ConfigInterface` represents a smaller impact to the code, and if it isn't a useful abstraction, then it isn't much of a logical/organizational impact either.

**Comment by dereuromark** [comment]
Are you able to provide a patch with your suggested changes as PR?

**Comment by cullylarson** [comment]
Sorry, I haven't really looked at this project for a few years. If I have reason to use it again in the future, I'd consider contributing.

**Comment by UlrichEckhardt** [comment]
FWIW, I just implemented a rough sketch of a configuration that's based on the interface but retrieves its values from a Symfony service container. The goal was to to integrate it into an existing application and provide e.g. `app/console phinx:migrate` and that seems to work so far.

BTW: What I found much more worrying was the fact that `ConfigInterface` implement `ArrayAccess`. However, none of the keys for that array are defined, so that's the least restrictive interface one could imagine, which in turn also offers the least amount of guarantees! AFAICT, the `ArrayAccess` functions are unused for simple migrations, so I'd suggest removing that in the first place. If the goal is to log the contents, I'd rather provide an explicit method to retrieve debug info or implement the `JsonSerializable` interface instead, which is read-only.
