### ISSUE TITLE
Migrations do not apply cleanly on MySQL with autocommit off

### ISSUE THREAD

**Issue by chris48s** [cakephp/phinx#750]
Steps to reproduce:
1. Add `autocommit=0` to my.cnf and restart mysqld
2. Create a migration, for example:

``` php
<?php
use Phinx\Migration\AbstractMigration;

class Initial extends AbstractMigration
{
    public function up()
    {
        $table = $this->table('foo');
        $table
            ->addColumn('bar', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->create();
    }
}
```
1. Run `phinx migrate`
2. The table foo will be created, but a record will not be added to the phinxlog table. Running `phinx status` will report that the migration is down, meaning the user is left in an inconsistent state.

**Comment by dereuromark** [comment]
Is anyone able to provide a pull request with a fix?

**Comment by lorenzo** [comment]
phinx does not rely anymore on the autocommit setting

**Comment by squatto** [comment]
@lorenzo I was writing an issue for this same thing and came across this closed issue. I think that this should actually be reopened because it's a genuine issue with what I am assuming would be a pretty easy solution.

When `autocommit` is turned off, the migration itself will run without any issues because it is wrapped in `START TRANSACTION`...`COMMIT`. However, the `phinxlog` insert is *not* in a transaction, which causes it to be discarded when the connection is closed. The result is that the same migration(s) are run again and they fail.

---

**Run migrations the first time:**

```
❯ php ../vendor/bin/phinx --configuration=./config/phinx.foo.php migrate -vv
Phinx by CakePHP - https://phinx.org. 0.11.1

using config file ./config/phinx.foo.php
using config parser php
using migration paths
 - /path/to/migrations/foo
using adapter mysql
using database foo

 == 20191227215237 AddSeparatePartsLaborCoreFieldsToArcCartItems: migrating
START TRANSACTION;

 -- Altering table arc_cart_items
 -- ...all migration queries...

COMMIT;

INSERT INTO `phinxlog` (`version`, `migration_name`, `start_time`, `end_time`, `breakpoint`) VALUES ('20191227215237', 'AddSeparatePartsLaborCoreFieldsToArcCartItems', '2019-12-30 11:50:15', '2019-12-30 11:50:15', 0);
 == 20191227215237 AddSeparatePartsLaborCoreFieldsToArcCartItems: migrated 0.1825s

All Done. Took 0.2923s
```

You can see that the migration queries ran in a transaction, but the `phinxlog` insert did not.

---

**Run migrations the second time:**

```
❯ php ../vendor/bin/phinx --configuration=./config/phinx.foo.php migrate -vv
Phinx by CakePHP - https://phinx.org. 0.11.1

using config file ./config/phinx.foo.php
using config parser php
using migration paths
 - /path/to/migrations/foo
using adapter mysql
using database foo

 == 20191227215237 AddSeparatePartsLaborCoreFieldsToArcCartItems: migrating
START TRANSACTION;

 -- Altering table arc_cart_items
InvalidArgumentException: The specified column doesn't exist: guru_item_id in /path/to/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php:491
Stack trace:
---STACK TRACE REMOVED---
```

Because the `phinxlog` entry was never actually inserted, the same migration is run again, which will obviously result in an error.

This could be fixed by using the same logic as the migrations themselves when doing the `phinxlog` insert:

1. if the engine has transactions, start a transaction
2. `INSERT INTO phinxlog ...`
3. if the engine has transactions, commit the transaction
