### ISSUE TITLE
How to mark a migration?

### ISSUE THREAD

**Issue by bupy7** [cakephp/phinx#892]
I have a migration that I have used. How me to mark "done" status? Or how me skip their? This migrations is structure the my project. I began use Phinx after wrote the structure.

**Comment by rquadling** [comment]
If your phinx log is empty, then you could sort of cheat by commenting out the migrations methods (all of them) and then running it.

Or you could add an appropriate entry into the `phinxlog` table (or whatever you have called it, if you have overridden the name).

**Comment by bupy7** [comment]
Have you in the plans to make the console command?

**Comment by rquadling** [comment]
It would be problematic to have the ability to mark a migration as done without it actually being done. The idea is to be able to rollback and migrate as often as necessary. If a migration has been performed manually, then there really is no need to have it in Phinx.

As for the initial schema, it is often the case that a physical schema dump exists prior to using migrations.

So your first migration could be as simple as detecting if a table from the initial schema exists and doing nothing otherwise executing the initial schema query to create the schema.

As there is no `down` migration, this only needs to be an `up`. Maybe something like ...

```php
<?php

use Phinx\Migration\AbstractMigration;

class InitialSchema extends AbstractMigration
{
    public function up()
    {
        if (!$this->hasTable('categories')) {
            $this->query(file_get_contents(__DIR__.'/initial-schema.sql'));
        }
    }
}
```

This allows new users to create the schema from the inital-schema.sql file. No rollback. Existing users will have no payload.

So, because this is such an edge case and easily solved within the existing Phinx mechanics, I don't see any reason to add an alternative mechanism.

Of course, if you can make a PR with functionality that is useful, then I'll certainly let the community decide.

**Comment by rquadling** [comment]
If your initial schema is written in phinx, then just adding the detection of the first table around the whole `up()` method body should be enough. 2 lines of code provides you with everything.

**Comment by bupy7** [comment]
@rquadling Ok. I shall be thought as to add mark command to Phinx. Example, in Yii2 Framework exists mark command in migration.
